### ISSUE TITLE
how to compile/make these files into a dll file?

### ISSUE THREAD

**Issue by TheRealGDEabarod** [josh33901/F1Public#6]
Hello.
I was wondering how you could get all of these files and make them into a .dll so I can inject it
Thanks

**Comment by josh33901** [comment]
compile it using visual studio. 
or download the latest version from the ci

**Comment by TheRealGDEabarod** [comment]
Sorry again, but how do I compile it from Visual Studio
I'm sort of a hacking noob :)
You can also leave a link to somewhere it tells me that
Thanks

**Comment by Rhodesia** [comment]
cant you also use build.bat?

**Comment by josh33901** [comment]
open the solution file. 
change the drop down from debug to release. 
f5 or use the drop down menus. 
this is more general, but should help: https://msdn.microsoft.com/en-us/library/jj620919.aspx

**Comment by josh33901** [comment]
make and _make should also work, provided you have the correct build tools installed.

**Comment by TheRealGDEabarod** [comment]
I will probably ask more questions later, but for now thanks

**Comment by Rhodesia** [comment]
if you arent editing anything just use https://ci.appveyor.com/project/josh33901/f1public/build/artifacts

**Comment by TheRealGDEabarod** [comment]
THANK YOU!! I WAS LOOKING FOR THAT! Why id i not find that?
Thanks, and signing off
Michael

**Comment by Rhodesia** [comment]
farewell space cowboy
